
const LAYOUT_63 = '9x7';
const LAYOUT_16 = '4x4';
const LAYOUT_6 = '2x3';
const TOTAL_CARDS = [60, 15, 4];
const CARD_IMAGES_PATH = 'cardImages';
const DOWNLOAD_COOLDOWN = 10000;
const DOWNLOADS_BEFORE_COOLDOWN = 10;

export {
	LAYOUT_63, LAYOUT_16, LAYOUT_6,
	TOTAL_CARDS,
	CARD_IMAGES_PATH,
	DOWNLOAD_COOLDOWN, DOWNLOADS_BEFORE_COOLDOWN
};